"""
Logical sub-groups for ordering parameters within each report category.
Each category maps to a list of (sub_group_name, [test_names]) tuples.
Parameters not listed in any sub-group appear under "Other" at the end.
"""

PARAMETER_SUBGROUPS = {

    # ── IMMUNE STATUS ──────────────────────────────────────────────────
    "Immune Status": [
        ("Leukocytes & Lymphocytes", [
            "Total Leukocytes [Leu]",
            "Total Lymphocytes [Lin]",
        ]),
        ("T Lymphocytes", [
            "T lymphocytes  [T]",
            "T4 lymphocytes [T4]",
            "T8 Lymphocytes [T8]",
            "Ratio T4/T8 [T4/T8]",
            "Activated T Lymphocytes [Tact]",
        ]),
        ("CD4+ T Cell Subsets", [
            "Activated T4 Lymphocytes [T4act]",
            "Lymphocytes T4 Helpers [T4H]",
            "Naïve T4 Lymphocytes [T4N]",
            "Ratio T4 helper/T4 naïve [T4h/T4n]",
            "Regulatory T4 Lymphocytes [Treg]",
            "T4 Central Memory Lymphocytes [T4 CM]",
            "T4 Effector Memory Lymphocytes [T4 EM]",
        ]),
        ("CD8+ T Cell Subsets", [
            "Activated T8 Lymphocytes [T8act]",
            "Cytotoxic T8 Lymphocytes [T8 cyto]",
            "Senescent T8 Lymphocytes [T8sen]",
            "Ratio T8 Cytotoxic / T8 Senescent [T8c/T8s]",
            "T8 Central Memory Lymphocytes [T8 CM]",
            "Memory Effector T8 Lymphocytes [T8 EM]",
        ]),
        ("Helper T Cell Profiles", [
            "TH1", "TH2", "TH1 / TH2",
            "TH17", "TH17;TH1", "TH17 / Tregs",
            "Tregs", "TH9", "TH22",
        ]),
        ("NK, NKT & B Cells", [
            "NK lymphocytes  [NK]",
            "NKT lymphocytes  [NKT]",
            "B lymphocytes [B]",
            "- B1a lymphocytes [B1a]",
        ]),
        ("Viral Serology", [
            "Herpes Simplex Type 1 IgG Ab [HSV1]",
            "Herpes Simplex Type 2 IgG Ab [HSV2]",
            "Citomegalovirus IgG Ab [CMV IgG]",
            "Epstein-Barr VCA IgM Ab   [VCA IgM]",
            "Epstein-Barr VCA IgG Ab [VCA IgG]",
            "Epstein-Barr Early IgG Ab  [EA IgG]",
            "Epstein-Barr Nuclear EBNA IgG Ab [EBNA IgG]",
            "Parvovirus B19 IgG Ab [PB19]",
            "Varicella Zoster IgG Ab [VZV]",
        ]),
        ("Monocytes", [
            "Monocytes [Mono]",
            "Classic monocytes [Mon C]",
            "Intermediate Monocytes [Mon In]",
            "Non-Classical Monocytes [Mon NC]",
        ]),
        ("Granulocytes", [
            "Neutrophils [Neu]",
            "Eosinophils [Eos]",
            "Basophils [Bas]",
        ]),
        ("Other Immune Markers", [
            "Interleucine-2 Soluble Receptor [IL2r]",
            "Selective reactivity of the immune system",
            "Global reactivity of the Immune System",
            "Immunotolerance",
            "Humoral immunity",
            "Innate Immunity",
        ]),
    ],

    # ── HEMOGRAM ───────────────────────────────────────────────────────
    "Hemogram": [
        ("Red Blood Cells", [
            "RBCs", "Hemoglobin", "Hematocrit",
            "MCV", "MCH", "MCHC", "RDW",
        ]),
        ("Platelets", [
            "Platelets", "MPV",
        ]),
        ("White Blood Cells", [
            "Total Leukocyte", "Neutrophils", "Lymphocytes",
            "Monocytes", "Eosinophyles", "Basophyles",
        ]),
    ],

    # ── INTESTINAL DYSBIOSIS BY NGS ────────────────────────────────────
    "Intestinal Dysbiosis by NGS": [
        ("Sample & Digestive Enzymes", [
            "Sample Analyzed",
            "pH",
            "Alpha glucosidase [a-Glucosi]",
            "Beta-glucosidase [\u00df-Glucosi]",
            "Beta glucuronidase [\u00df-Glucuro]",
            "Pancreatic elastase 1 [Elast]",
        ]),
        ("Gut Barrier & Inflammation", [
            "Fecal Occult Blood [FOB]",
            "Calprotectin [Calp]",
            "sIgA Secretory [IgAs]",
            "Alpha-1 antitrypsin  [AntiTrypsin]",
            "Zonulin [Zonul]",
            "Eosinophil Protein X [EPX]",
        ]),
        ("Short-Chain Fatty Acids", [
            "TOTAL SCFA",
            "SCFA Beneficial [SCFA Bene]",
            "SCFA Putrefactive [SCFA Putr]",
            "Acetic Acid % [Acetic Ac]",
            "- Propionic [Prop]",
            "Butyric Acid % [Butyric Ac]",
            "Valeric Acid [Ac Valeric]",
            "iso-Valeric Acid  [Ac IsoVal]",
            "iso-Butyric Acid  [Ac isoButiric]",
            "Caproic Acid  [Ac Caproic]",
            "iso-Caproic Acid  [Ac isoCaproic]",
            "Protein SCFAs [SCFA Prot]",
        ]),
        ("Bacterial Composition Overview", [
            "Bacteria [BACT]",
            "Bacillota+Bacteridota [Bacil+Bacter]",
            "Bacillota/Bacteridota [Bacil/Bacter]",
            "Muconutritive Bacteria [MUCO]",
            "Regulatory Bacteria [REG]",
            "Proteolytic Bacteria [PROT]",
            "Other Bacteria [OTH]",
        ]),
        ("Key Beneficial Bacteria", [
            "Akkermansia [Akker]",
            "- Akkermansia muciniphila",
            "Faecalibacterium [Faecal]",
            "- Faecalibacterium prausnitzii",
            "Roseburia [Roseb]",
            "- Roseburia intestinalis",
            "Eubacterium [Eubac]",
            "Blautia [Blaut]",
            "Bifidobacterium [Bifido]",
            "- Bifidobacterium adolescentis",
        ]),
        ("Lactobacillaceae", [
            "Lactobacillaceae [Lacto]",
            "- Limosylactobacillus",
            "- Lacticaseibacillus",
            "- Ligilactobacillus",
            "- Lactobacillus",
            "- Lactiplantibacillus",
            "- Leuconostoc",
            "- Weissella",
            "- Lactobacillus acidophilus",
        ]),
        ("Commensal Bacteria", [
            "Bacteroides [Bacter]",
            "- Bacteroides fragilis",
            "- Bacteroides thetaiotaomicron",
            "Prevotella [Prevot]",
            "- Prevotella copri",
            "Alistipes [Alist]",
            "- Phocaeicola vulgatus",
            "Ruminococcus [Rumin]",
            "Veillonella [Veillo]",
            "Collinsella [Collin]",
            "- Collinsella aerofaciens",
            "Propionibacterium [Prop]",
            "Bacillus [Bacil]",
            "Enterococcus [Enter]",
            "- Enterococcus faecalis",
            "- Enterococcus faecium",
            "Staphylococcus [Staph]",
            "- Staphylococcus aureus",
            "Streptococcus [Strept]",
            "- Streptococcus thermophilus",
            "Clostridium [Clost]",
            "- Clostridium butyricum",
            "- Clostridium perfringens",
            "Clostridioides [Closdd]",
            "- Clostridiodes difficile",
            "- Mediterraneibacter gnavus",
        ]),
        ("Enterobacteriales & Potential Pathogens", [
            "Enterobacteriales [ETBs]",
            "- Escherichia",
            "- Escherichia coli",
            "- Shigella",
            "- Salmonella",
            "- Klebsiella",
            "- Klebsiella pneumoniae",
            "- Yersinia",
            "- Yersinia enterocolitica",
            "- Proteus",
            "- Proteus mirabilis",
            "- Hafnia alvei",
            "- Pseudomonas putida",
            "- Campylobacter jejuni",
            "- Fusobacterium nucleatum",
            "Oxalobacter [Oxal]",
            "Pseudomonas [Pseu]",
            "Campylobacter [Camp]",
            "Helicobacter [Helic]",
            "Fusobacterium [Fusob]",
            "Desulfovibrio [DSulfo]",
            "Desulfurivibrio [DSulfu]",
            "Helicobacter Pylori. Antigen [Ag H. pylor]",
        ]),
        ("Functional Assessments", [
            "Muconutritive",
            "Regulatory",
            "Proteolytic",
            "LPS",
            "Symbionts",
            "Pathobionts",
            "Toxins",
            "DNA",
            "Digestion",
            "Vitamins",
            "Permeability",
            "SIBO",
            "LIBO",
            "IMO",
            "ISO",
        ]),
        ("Mucin Degradation", [
            "Mucin Degradation [Deg Muc]",
            "- Sialidases",
            "- Fucosidases",
            "- Galactosidases",
            "- Sulfatases",
            "- N-acetylglucosaminidases",
            "- Proteases",
        ]),
        ("LPS Pathway", [
            "[LPS] or lipopolysaccharides",
            "- Lipid A synthesis",
            "- Formation of the O antigen",
            "- Post-synthesis modification",
        ]),
        ("Archaea", [
            "Archaea [ARCH]",
            "Methanogens [MET]",
            "- Methanobrevibacter smithii",
            "- Methanosphaera stadtmanae",
            "- Methanomassiliicoccus luminyensis",
            "Methanobrevibacter [MBrev]",
            "Methanocella [MCell]",
            "Methanofolis [MFolis]",
            "Methanosarcin [MSarc]",
            "Methanosphaera [MSpha]",
            "Thermococcus [Thermc]",
            "Desulfurococcus [Desulf]",
            "Metanophiles",
            "Halophylls",
            "Sulfurous",
            "Archaeas. Others",
            "Halophilic [HAL]",
            "Nitrophils [NIT]",
            "Sulphurous [SULF]",
            "Thermophiles [TERM]",
            "Others [MIX]",
        ]),
        ("Fungi & Yeasts", [
            "Fungi and Yeasts [FUNG]",
            "Fungi [FUNG]",
            "Yeasts [YEA]",
            "- Candida albicans",
            "- Saccharomyces cerevisiae",
            "- Fusarium proliferatum",
            "- Debaryomyces hansenii",
            "Candida",
            "Mycotoxins",
            "Skin",
            "Environmental",
            "Saccharomyces [Sacc]",
            "Zygosaccharomyces [ZSacc]",
            "Alternaria [Alter]",
            "Aspergillus [Asper]",
            "Candida [Cand]",
            "Fusarium [Fusar]",
            "Neurospora [Neuros]",
            "Penicillium [Penic]",
            "Cryptococcus [Crypt]",
            "Malassezia [Malas]",
            "Rhodotorula [Rhodo]",
            "Trichosporon [Tricho]",
            "Others [OTH]",
        ]),
        ("Viruses", [
            "Viruses [VIR]",
            "Phages [Phages]",
            "Pathogens [Patog]",
            "Others",
        ]),
        ("Parasites & Helminths", [
            "Parasites",
            "Helminths",
            "Parasites and Helminths [PAR]",
            "Blastocystis [Blast]",
            "Giardia [Giar]",
            "Cryptosporidium [Cryp]",
            "Enterocytozoon [Entzo]",
            "Enterobius [Enter]",
            "Ascaris [Asca]",
            "Anisakis [Anis]",
            "Fasciola [Fasc]",
        ]),
    ],

    # ── BACTERIOMA BY NGS ──────────────────────────────────────────────
    "Bacterioma by NGS": [
        ("Overview & Diversity", [
            "Bacterium",
            "Shannon index",
            "Richness",
            "Enterotype",
            "Bacillota+bacteroidota",
            "Bacillota/Bacteroidota",
            "Bacteroides/Prevotella",
        ]),
        ("Functional Groups", [
            "Muconutritive",
            "Regulatory",
            "Proteolytic",
            "Others",
        ]),
        ("Phyla Distribution", [
            "Bacillota (Firmicutes)",
            "Bacteroidota (Bacteroidetes)",
            "Actinomycetota",
            "Pseudomonadota",
            "Campylobacterota",
            "Fusobacteriota",
            "Verrucomicrobiota",
            "Thermodesulfobacteriota",
            "Spirochaetota",
        ]),
        ("E. coli", [
            "Escherichia coli",
            "Pathogenic strains",
            "- EHEC/STEC", "- ETEC", "- EAEC", "- ExPEP",
            "Symbiotic strains",
            "- Escherichia coli Nissle 1917",
            "Other strains",
        ]),
        ("Bacillota - Key Genera", [
            "Faecalibacterium",
            "- F. duncaniae", "- F. prausnitzii",
            "Roseburia",
            "- R. intestinalis", "- R. hominis",
            "Blautia",
            "- B. wexlerae", "- B. obeum", "- B. product",
            "Ruminococcus",
            "- R. champanellensis", "- R. bicirculans", "- R. bovis",
            "Eubacterium",
            "Coprococcus",
            "Agathobacter",
            "Anaerobutyricum",
            "Anaerostipes",
            "Butyrivibrio",
            "Dorea",
            "Lachnoclostridium",
            "Lachnospira",
            "Oscillibacter",
            "Dysosmobacter",
            "Flavonifractor",
            "Hungatella",
            "Intestines",
            "Phascolarctobacterium",
            "Veillonella",
            "Vescimonas",
            "Megamonas",
            "Megasphaera",
            "Dialister",
            "Selenomonas",
            "Catenibacterium",
            "Christensenella",
            "Holdemanella",
            "Ruthenibacterium",
        ]),
        ("Bacillota - Lactobacillales & Cocci", [
            "Lactobacillus",
            "Lacticaseibacillus",
            "Lactiplantibacillus",
            "Ligilactobacillus",
            "Limosylactobacillus",
            "Lactococcus",
            "Leuconostoc",
            "Weissella",
            "Pediococcus",
            "Enterococcus",
            "- E. faecalis",
            "- E. faecium",
            "Streptococcus",
            "- S. agalactiae", "- S. salivarius",
            "- S. thermophilus",
            "Staphylococcus",
            "Aerococcus",
            "Gemella",
            "Bacillus",
            "- B. subtilis",
            "Vagococcus",
        ]),
        ("Bacillota - Clostridia & Others", [
            "Clostridium",
            "- C. butyricum", "- C. perfringens", "- C. sporogenes",
            "Clostridioides",
            "- C. difficile",
            "Enterocloster",
            "Thomasclavelia",
            "Mediterraneibacter",
            "- M. gnavus", "- M. lactaris", "- M. torques",
            "Anaerococcus",
            "Ezakiella",
            "Faecalibacillus",
            "Fenollaria",
            "Finegoldia",
            "Ethanoligenens",
            "Listeria",
            "Mageeibacillus",
            "Parvimonas",
            "Peptococcus",
            "Peptoniphilus",
            "Peptostreptococcus",
            "Simiaoa",
            "Solobacterium",
            "Wujia",
        ]),
        ("Bacteroidota Genera", [
            "Bacteroids",
            "- B. fragilis", "- B. ovatus", "- B. salyersiae",
            "- B. thetaiotaomicron", "- B. uniformis",
            "Prevotella",
            "- P. copri", "- P. intermedia",
            "- P. melaninogenica", "- P. nigrescens",
            "Alistipes",
            "- A. communis", "- A. dispar", "- A. finegoldii", "- A. onderdonkii",
            "Phocaeicola",
            "- P. dorei", "- P. salanitronis", "- P. vulgatus",
            "Parabacteroids",
            "Barnesiella",
            "Butyricimonas",
            "Capnocytophaga",
            "Dysgonomonas",
            "Flavobacterium",
            "Odoribacter",
            "Paraprevotella",
            "Porphyromonas",
            "Tannerella",
        ]),
        ("Actinomycetota Genera", [
            "Bifidobacterium",
            "- B. adolescentis", "- B. animalis", "- B. longum",
            "- B. bifidum", "- B. pseudocatenulatum",
            "Collinsella",
            "- C. aerofaciens",
            "G Actinomyces",
            "Atopobium",
            "Actinotignum",
            "Brevibacterium",
            "Corynebacterium",
            "Cutibacterium",
            "Eggerthella",
            "Fannyhessea",
            "Gardnerella",
            "Gordonibacter",
            "Kocuria",
            "Lancefieldella",
            "Micrococcus",
            "Mobiluncus",
            "Olsenella",
            "Propionibacterium",
            "- P. freudenreichii",
            "Rothia",
            "Schaalia",
            "Streptomyces",
            "Vaginimicrobium",
            "Varibaculum",
            "Winkia",
        ]),
        ("Pseudomonadota Genera", [
            "Escherichia",
            "- E.coli",
            "Klebsiella",
            "- K. pneumoniae",
            "Shigella",
            "Salmonella",
            "Enterobacter",
            "Citrobacter",
            "Cronobacter",
            "Hafnia",
            "Morganella",
            "Proteus",
            "Providencia",
            "Raoultella",
            "Serratia",
            "Yersinia",
            "Pseudomonas",
            "Acinetobacter",
            "Aeromonas",
            "Aggregatibacter",
            "Alteromonadaceae",
            "Alteromonas",
            "Bartonella",
            "Bilophila",
            "Bordetella",
            "Brucella",
            "Burkholderia",
            "Comamonas",
            "Delftia",
            "Eikenella",
            "Erwinia",
            "Haemophilus",
            "Kinneretia",
            "Legionella",
            "Neisseria",
            "Hoylesella",
            "Oxalobacter",
            "Moraxella",
            "Paracoccus",
            "Ralstonia",
            "Paraglaciecola",
            "Pasteurella",
            "Rhizobium",
            "Roseateles",
            "Sphingomonas",
            "Stenotrophomonas",
            "Sutterella",
        ]),
        ("Other Phyla Genera", [
            "Desulfovibrio",
            "Desulfurivibrio",
            "Campylobacter",
            "- C.coli", "- C. jejuni",
            "Desulfurella",
            "Helicobacter",
            "Sulfurimones",
            "Fusobacterium",
            "Ilyobacter",
            "Leptotrichia",
            "Pseudoleptotrichia",
            "Sneathia",
            "Akkermansia",
            "- A. muciniphila",
            "Lentimonas",
            "Rubritalea",
            "Borrelia",
            "Brachyspira",
            "Leptospira",
            "Treponema",
        ]),
    ],

    # ── ARCHAEOMA BY NGS ───────────────────────────────────────────────
    "Archaeoma by NGS": [
        ("Overview & Diversity", [
            "Archaea",
            "Shannon Index",
            "Richness",
        ]),
        ("Functional Groups", [
            "Methanogens",
            "Sulphurous",
            "Halophylls",
            "Thermophiles",
            "Nitrophils",
            "Others (multiple functionality)",
        ]),
        ("Methanogens", [
            "Methanobacterium",
            "Methanobrevibacter",
            "- M. smithii",
            "- M. millerae",
            "- M. olleyae",
            "Methanocaldococcus",
            "Methanocella",
            "Methanococcoides",
            "Methanococcus",
            "Methanocorpusculum",
            "Methanoculleus",
            "Methanofervidicoccus",
            "Methanofolis",
            "Methanohalophilus",
            "Methanomicrobium",
            "Methanoplanus",
            "Methanopyrus",
            "Methanoregula",
            "Methanosarcina",
            "Methanosphaera",
            "Methanospirilium",
            "Methanothermobacter",
            "Methanothrix",
            "Methanomassiliicoccus",
        ]),
        ("Halophilic Archaea", [
            "Cuniculiplasma",
            "Haladaptatus",
            "Halapricum",
            "Halobacterium",
            "Halobaculum",
            "Haloferaz",
            "Halogeometricum",
            "- H. borinquense",
            "Halorussus",
            "Halovivax",
            "Salinirubellus",
            "- S. salinus",
        ]),
        ("Thermophiles & Others", [
            "Pyrococcus",
            "Thermococcus",
            "Desulfurococcus",
            "Sulfolobus",
            "Ferroglobus",
            "Geoglobus",
            "Nitrosopumilus",
            "Nitrososphaera",
            "Nanoarchaeum",
        ]),
    ],

    # ── MYCOBIOME BY NGS ───────────────────────────────────────────────
    "Mycobiome by NGS": [
        ("Overview & Diversity", [
            "Fungi",
            "Shanon index",
            "Richness",
            "Yeasts",
            "Fungus",
            "Others",
        ]),
        ("Ascomycota (Yeasts)", [
            "Saccharomyces",
            "- S. cerevisiae",
            "Candida Group",
            "Debaryomyces",
            "Eremothecium",
            "Geotrichum",
            "Komagataella",
            "Metschnikowia",
            "Ogataea",
            "Schizosaccharomyces",
            "Torulaspora",
            "Wickerhamomyces",
            "Yarrowia",
            "Zygosaccharomyces",
        ]),
        ("Ascomycota (Filamentous Fungi)", [
            "Alternaria",
            "Aspergillus",
            "- A. heteromorphus",
            "Blastomyces",
            "Botrytis",
            "Chaetomium",
            "Claviceps",
            "Colletotrichum",
            "Exophiala",
            "Fonsecaea",
            "Fusarium",
            "- F. proliferatum",
            "Grosmannia",
            "Histoplasma",
            "Morchella",
            "Neurospora",
            "Penicillium",
            "- P. rubens",
            "Pneumocystis",
            "Pyricularia",
            "Sporothrix",
            "Talaromyces",
            "Trichoderma",
            "Trichophyton",
        ]),
        ("Basidiomycota", [
            "Apiotrichum",
            "Cryptococcus",
            "Cutaneotrichosporon",
            "Dacryopinax",
            "Malassezia",
            "- Malassezia pachydermatis",
            "Moesziomyces",
            "Pseudozyma",
            "Puccinia",
            "Rhodotorula",
            "Schizophyllum",
            "Sporisorium",
            "Trichosporon",
            "Ustilago",
            "Wallemia",
        ]),
        ("Zygomycota", [
            "Mucor",
            "Phycomyces",
            "- P. blakesleeanus",
            "Rhizopus",
            "Umbelopsis",
        ]),
    ],

    # ── VIROME BY NGS ──────────────────────────────────────────────────
    "Virome by NGS": [
        ("Overview & Diversity", [
            "Virus",
            "Shannon Index",
            "Richness",
        ]),
        ("Phages - Abundance", [
            "TOTAL Phages [Phages]",
            "- Bacteriophages",
            "Faecalibacterium phage",
            "Phage Bacteroides",
            "Parabacteroides phage",
            "Bacteroidota phage",
            "Salmonella phage",
            "Enterobacteria phage",
            "Escherichia phage",
            "Shigella phage",
            "Stx2 phage",
            "Streptococcus phage",
            "Staphylococcus phage",
            "Lactococcus phage",
            "Enterobacter phage",
            "Klebsiella phage",
            "- other Phages",
        ]),
        ("Virus-to-Microbe Ratios (VMR)", [
            "Enterococcus",
            "Streptococcus",
            "Faecalibacterium",
            "Lactococcus",
            "Bacteroidota",
            "Bacteroids",
            "Parabacteroids",
            "Streptomyces",
            "Clostridium",
            "Hafnia",
            "Escherichia",
            "Klebsiella",
            "Shigella",
            "Bacillus",
            "Salmonella",
            "Pseudomonas",
            "Enterobacter",
        ]),
        ("Pathogenic Viruses", [
            "TOTAL Pathogens [Pathog]",
            "- DNA viruses",
            "- Retroviruses",
            "Others",
        ]),
    ],

    # ── PARASITOME BY NGS ──────────────────────────────────────────────
    "Parasitome by NGS": [
        ("Protozoa", [
            "Blastocystis sp.",
            "- Predominant species",
            "Acanthamoeba",
            "Entamoeba",
            "Giardia",
            "Spinonucleus",
            "Monocercomonoids",
            "Cyclospora",
            "Cystoisospora",
            "Cryptosporidium",
            "Eimeria",
            "Neospora",
        ]),
        ("Microsporidia", [
            "Anncaliia",
            "Enterospora",
            "Hepatospora sp.",
            "Mitosporidium sp.",
            "Enterocytozoon sp.",
        ]),
        ("Helminths", [
            "Enterobius",
            "Ascaris",
            "Strongyloides",
            "Trichuris",
            "Necator sp.",
            "Ancylostoma",
            "Anisakis",
            "Hymenolepis",
            "Taenia",
            "Fasciola",
        ]),
    ],

    # ── STOOL SAMPLE ───────────────────────────────────────────────────
    "Stool Sample": [
        ("Stool Markers", [
            "EPX [Protein X Eosinophilic]",
        ]),
    ],
}
